
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.dows;

import java.util.logging.Logger;

import org.dows.command.RequestProcessor;

/**
 * This class was generated by Apache CXF 2.1.3
 * Tue Feb 24 15:28:21 IST 2009
 * Generated source version: 2.1.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "BookLookup",
                      portName = "BookLookupPort",
                      targetNamespace = "http://www.doc-oriented-ws.org/BookLookup/",
                      wsdlLocation = "file:src/BookLookup.wsdl",
                      endpointInterface = "org.dows.BookLookup")
                      
public class BookLookupImpl implements BookLookup {

    private static final Logger LOG = Logger.getLogger(BookLookupImpl.class.getName());

    /* (non-Javadoc)
     * @see org.dows.BookLookup#process(org.dows.LookupRequest  lookupRequest )*
     */
    public org.dows.LookupResponse process(LookupRequest lookupRequest) { 
        LOG.info("Executing operation process");
        try {
            RequestProcessor rp = new RequestProcessor(lookupRequest);
            return rp.process();
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
