
package org.dows;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.1.3
 * Tue Feb 24 15:28:21 IST 2009
 * Generated source version: 2.1.3
 * 
 */
 
public class TestBookLookup_TestBookLookupPort_Server{

    protected TestBookLookup_TestBookLookupPort_Server() throws Exception {
        System.out.println("Starting Server");
        Endpoint.publish("http://localhost:9009/cxf/test_book_lookup/", new TestBookLookupImpl());
    }
    
    public static void main(String args[]) throws Exception { 
        new TestBookLookup_TestBookLookupPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
