
package org.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.1.3
 * Tue Feb 24 15:36:28 IST 2009
 * Generated source version: 2.1.3
 * 
 */

public final class TestBookLookup_TestBookLookupPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.doc-oriented-ws.org/BookLookup/", "BookLookup");

    private TestBookLookup_TestBookLookupPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = BookLookup_Service.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BookLookup_Service ss = new BookLookup_Service(wsdlURL, SERVICE_NAME);
        TestBookLookup port = ss.getTestBookLookupPort();  
        
        {
        System.out.println("Invoking setupBooks...");
        java.lang.String _setupBooks_dBcsvpart = "";
        port.setupBooks(_setupBooks_dBcsvpart);


        }

        System.exit(0);
    }

}
