package org.client;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.3
 * Tue Feb 24 15:36:28 IST 2009
 * Generated source version: 2.1.3
 * 
 */
 
@WebService(targetNamespace = "http://www.doc-oriented-ws.org/BookLookup/", name = "TestBookLookup")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TestBookLookup {

    @Oneway
    @WebMethod(action = "http://www.doc-oriented-ws.org/TestBookLookup/setupBooks")
    public void setupBooks(
        @WebParam(partName = "DBcsvpart", name = "DBcsvee", targetNamespace = "http://www.doc-oriented-ws.org/BookLookup/")
        java.lang.String dBcsvpart
    );
}
